spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

clients:
  inventory: ${INVENTORY_URL}

server:
  port: ${SERVER_PORT:8080}