spring:
  application:
    name: product-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_BASE_URL}/auth/realms/e-com
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        registration:
          product-service:
            client-id: product-service
            client-secret: OKyHgoIvtRWlVAAtw1AQJBl4ZtSjm9Ov
            authorization-grant-type: client_credentials
        provider:
          keycloak-provider:
            token-uri: ${KEYCLOAK_BASE_URL}/auth/realms/e-com/protocol/openid-connect/token

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  auth:
    resource-id: access-token

clients:
  inventory: ${INVENTORY_URL}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.example.productservice.client.InventoryClient: DEBUG